name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
        with:
          version: 0.16.0

      - name: Run zig fmt
        if: matrix.os == 'ubuntu-22.04'
        run: zig fmt --check .

      - name: Run zig build check test
        run: zig build check test --summary all

      - name: Setup wasmtime
        if: matrix.os == 'ubuntu-22.04'
        uses: bytecodealliance/actions/wasmtime/setup@9152e710e9f7182e4c29ad218e4f335a7b203613 # v1.1.3

      - name: Run zig build check test -Dtarget=wasm32-
        if: matrix.os == 'ubuntu-22.04'
        run: zig build check test -Dtarget=wasm32-wasi -fwasmtime --summary all

  build-nix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7.0.2
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-

      - run: |
          nix build -L .#zls
